import { langOptions } from "src/main";

export const LANG_OPTIONS: langOptions[] = [
	{ label: "Empty", isoCode: "empty" },
	{ label: "Afrikaans", isoCode: "af" },
	{ label: "Albanian", isoCode: "sq" },
	{ label: "Amharic", isoCode: "am" },
	{ label: "Arabic", isoCode: "ar" },
	{ label: "Armenian", isoCode: "hy" },
	{ label: "Azerbaijani", isoCode: "az" },
	{ label: "Basque", isoCode: "eu" },
	{ label: "Belarusian", isoCode: "be" },
	{ label: "Bengali", isoCode: "bn" },
	{ label: "Bosnian", isoCode: "bs" },
	{ label: "Bulgarian", isoCode: "bg" },
	{ label: "Catalan", isoCode: "ca" },
	{ label: "Cebuano", isoCode: "ceb" },
	{ label: "Chinese (Simplified)", isoCode: "zh-cn" },
	{ label: "Chinese (Traditional)", isoCode: "zh-tw" },
	{ label: "Corsican", isoCode: "co" },
	{ label: "Croatian", isoCode: "hr" },
	{ label: "Czech", isoCode: "cs" },
	{ label: "Danish", isoCode: "da" },
	{ label: "Dutch", isoCode: "nl" },
	{ label: "English", isoCode: "en" },
	{ label: "Esperanto", isoCode: "eo" },
	{ label: "Estonian", isoCode: "et" },
	{ label: "Finnish", isoCode: "fi" },
	{ label: "French", isoCode: "fr" },
	{ label: "Frisian", isoCode: "fy" },
	{ label: "Galician", isoCode: "gl" },
	{ label: "Georgian", isoCode: "ka" },
	{ label: "German", isoCode: "de" },
	{ label: "Greek", isoCode: "el" },
	{ label: "Gujarati", isoCode: "gu" },
	{ label: "Haitian Creole", isoCode: "ht" },
	{ label: "Hausa", isoCode: "ha" },
	{ label: "Hawaiian", isoCode: "haw" },
	{ label: "Hebrew", isoCode: "he" },
	{ label: "Hindi", isoCode: "hi" },
	{ label: "Hmong", isoCode: "hmn" },
	{ label: "Hungarian", isoCode: "hu" },
	{ label: "Icelandic", isoCode: "is" },
	{ label: "Igbo", isoCode: "ig" },
	{ label: "Indonesian", isoCode: "id" },
	{ label: "Irish", isoCode: "ga" },
	{ label: "Italian", isoCode: "it" },
	{ label: "Japanese", isoCode: "ja" },
	{ label: "Javanese", isoCode: "jv" },
	{ label: "Kannada", isoCode: "kn" },
	{ label: "Kazakh", isoCode: "kk" },
	{ label: "Khmer", isoCode: "km" },
	{ label: "Korean", isoCode: "ko" },
	{ label: "Kurdish", isoCode: "ku" },
	{ label: "Kyrgyz", isoCode: "ky" },
	{ label: "Lao", isoCode: "lo" },
	{ label: "Latin", isoCode: "la" },
	{ label: "Latvian", isoCode: "lv" },
	{ label: "Lithuanian", isoCode: "lt" },
	{ label: "Luxembourgish", isoCode: "lb" },
	{ label: "Macedonian", isoCode: "mk" },
	{ label: "Malagasy", isoCode: "mg" },
	{ label: "Malay", isoCode: "ms" },
	{ label: "Malayalam", isoCode: "ml" },
	{ label: "Maltese", isoCode: "mt" },
	{ label: "Maori", isoCode: "mi" },
	{ label: "Marathi", isoCode: "mr" },
	{ label: "Mongolian", isoCode: "mn" },
	{ label: "Myanmar (Burmese)", isoCode: "my" },
	{ label: "Nepali", isoCode: "ne" },
	{ label: "Norwegian", isoCode: "no" },
	{ label: "Nyanja (Chichewa)", isoCode: "ny" },
	{ label: "Odia (Oriya)", isoCode: "or" },
	{ label: "Pashto", isoCode: "ps" },
	{ label: "Persian", isoCode: "fa" },
	{ label: "Polish", isoCode: "pl" },
	{ label: "Portuguese", isoCode: "pt" },
	{ label: "Portuguese Brazil", isoCode: "pt-br" },
	{ label: "Punjabi", isoCode: "pa" },
	{ label: "Romanian", isoCode: "ro" },
	{ label: "Russian", isoCode: "ru" },
	{ label: "Samoan", isoCode: "sm" },
	{ label: "Scots Gaelic", isoCode: "gd" },
	{ label: "Serbian", isoCode: "sr" },
	{ label: "Sesotho", isoCode: "st" },
	{ label: "Shona", isoCode: "sn" },
	{ label: "Sindhi", isoCode: "sd" },
	{ label: "Sinhala (Sinhalese)", isoCode: "si" },
	{ label: "Slovak", isoCode: "sk" },
	{ label: "Slovenian", isoCode: "sl" },
	{ label: "Somali", isoCode: "so" },
	{ label: "Spanish", isoCode: "es" },
	{ label: "Sundanese", isoCode: "su" },
	{ label: "Swahili", isoCode: "sw" },
	{ label: "Swedish", isoCode: "sv" },
	{ label: "Tagalog (Filipino)", isoCode: "tl" },
	{ label: "Tajik", isoCode: "tg" },
	{ label: "Tamil", isoCode: "ta" },
	{ label: "Tatar", isoCode: "tt" },
	{ label: "Telugu", isoCode: "te" },
	{ label: "Thai", isoCode: "th" },
	{ label: "Turkish", isoCode: "tr" },
	{ label: "Turkmen", isoCode: "tk" },
	{ label: "Ukrainian", isoCode: "uk" },
	{ label: "Urdu", isoCode: "ur" },
	{ label: "Uyghur", isoCode: "ug" },
	{ label: "Uzbek", isoCode: "uz" },
	{ label: "Vietnamese", isoCode: "vi" },
	{ label: "Welsh", isoCode: "cy" },
	{ label: "Xhosa", isoCode: "xh" },
	{ label: "Yiddish", isoCode: "yi" },
	{ label: "Yoruba", isoCode: "yo" },
	{ label: "Zulu", isoCode: "zu" },
];
